pipeline:
  test:
    image:  amarburg/covis-postprocess:${DRONE_REPO_OWNER}-latest
    commands:
      - ls -al

  ## Build a test docker image
  build_docker:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t amarburg/covis-worker:latest \
              -t amarburg/covis-worker:${DRONE_REPO_OWNER}-latest \
              -t amarburg/covis-worker:${DRONE_REPO_OWNER}-${DRONE_COMMIT_SHA} .

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
