pipeline:
  test:
    image:  amarburg/covis-postprocess:${DRONE_REPO_OWNER}-latest
    commands:
      - ls -al

  build_docker:
    image: plugins/docker
    build_args:
      - BASE_IMAGE=${DRONE_REPO_OWNER}-latest

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
