pipeline:
  test:
    image:  amarburg/covis-worker:latest
    commands:
      - ./wait-for-it.sh -h old_covis_nas -p 9000
      - ./wait-for-it.sh -h new_covis_nas -p 9000
      - ./wait-for-it.sh -h mongodb -p 27017
      - make test

  # slack:
  #   image: plugins/slack
  #   secrets: [ slack_webhook ]
  #   when:
  #     status:
  #       - success
  #       - failure


services:
  mongodb:
    image: 'bitnami/mongodb:3.6'

  old_covis_nas:
    image: 'covis-worker/minio_old_nas'
    environment:
      - MINIO_ACCESS_KEY=covis
      - MINIO_SECRET_KEY=coviscovis

  new_covis_nas:
    image: 'covis-worker/minio_new_nas'
    environment:
      - MINIO_ACCESS_KEY=covis
      - MINIO_SECRET_KEY=coviscovis
