## This compose is _only used for local testing_
# Data is not persisted
#
version: '3'

services:
  mongodb:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"

  minio_nas:
    image: 'minio/minio'
    ports:
      - "9001:9000"
    environment:
     - MINIO_ACCESS_KEY=covis
     - MINIO_SECRET_KEY=coviscovis
    command: server /data
    volumes:
      - ./test_data/covis-nas/:/data
