## This compose is _for local testing_
# Data is not persisted
version: '3'

services:
  mongodb:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"

  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'

  minio_old_covis_nas:
    image: 'amarburg/covis_test_minio_old_nas'
    ports:
      - "9001:9000"
    environment:
     - MINIO_ACCESS_KEY=covis
     - MINIO_SECRET_KEY=coviscovis

  minio_new_covis_nas:
    image: 'amarburg/covis_test_minio_new_nas'
    ports:
      - "9000:9000"
    environment:
     - MINIO_ACCESS_KEY=covis
     - MINIO_SECRET_KEY=coviscovis
