version: '2'

networks:
  covis:
    driver: bridge

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    networks:
      - covis

  worker:
    build: .
    depends_on:
      - rabbitmq
    networks:
      - covis
    links:
      - rabbitmq
