#
# Launches all services necessary _for local testing_
# Data is not persisted
version: '3'

services:
  mongodb:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"

  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'

  minio-old-nas1:
    image: 'covis-worker/covis_test_minio'
    ports:
      - "9001:9000"
    volumes:
      - ./covis-test-data/old-covis-nas1/:/data
    environment:
     - MINIO_ACCESS_KEY=covis
     - MINIO_SECRET_KEY=coviscovis

  minio-new-nas:
    image: 'covis-worker/covis_test_minio'
    ports:
      - "9000:9000"
    volumes:
      - ./covis-test-data/new-covis-nas/:/data
    environment:
     - MINIO_ACCESS_KEY=covis
     - MINIO_SECRET_KEY=coviscovis

  sftp:
    image: 'atmoz/sftp:debian'
    ports:
      - '2222:22'
    volumes:
      - ./covis-test-data/sftp-host:/home/covis
      - ./tmp/ssh_keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./tmp/ssh_keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./tmp/ssh_keys/id_rsa.pub:/home/covis/.ssh/keys/id_rsa.pub
    environment:
      - SFTP_USERS=covis:coviscovis
