## This compose is _only used for local testing_
# Data is not persisted
#
version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
